# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qtUI/Openkiosk.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1024, 600)
        Dialog.setStatusTip("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 731, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setBold(True)
        font.setWeight(75)
        self.LeftLabel.setFont(font)
        self.LeftLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.LeftLabel.setObjectName("LeftLabel")
        self.horizontalLayout.addWidget(self.LeftLabel)
        self.MidLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setBold(True)
        font.setWeight(75)
        self.MidLabel.setFont(font)
        self.MidLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.MidLabel.setObjectName("MidLabel")
        self.horizontalLayout.addWidget(self.MidLabel)
        self.RightLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setBold(True)
        font.setWeight(75)
        self.RightLabel.setFont(font)
        self.RightLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.RightLabel.setObjectName("RightLabel")
        self.horizontalLayout.addWidget(self.RightLabel)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(760, 20, 251, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ItemList = QtWidgets.QListView(self.verticalLayoutWidget)
        self.ItemList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ItemList.setObjectName("ItemList")
        self.verticalLayout.addWidget(self.ItemList)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.ResultLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("나눔고딕 ExtraBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ResultLabel.setFont(font)
        self.ResultLabel.setObjectName("ResultLabel")
        self.verticalLayout.addWidget(self.ResultLabel)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 280, 731, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LeftInfo = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.LeftInfo.setFont(font)
        self.LeftInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.LeftInfo.setObjectName("LeftInfo")
        self.horizontalLayout_2.addWidget(self.LeftInfo)
        self.MidInfo = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.MidInfo.setFont(font)
        self.MidInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.MidInfo.setObjectName("MidInfo")
        self.horizontalLayout_2.addWidget(self.MidInfo)
        self.RightInfo = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.RightInfo.setFont(font)
        self.RightInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.RightInfo.setObjectName("RightInfo")
        self.horizontalLayout_2.addWidget(self.RightInfo)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 370, 731, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 731, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.LeftBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.LeftBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.LeftBtn.setObjectName("LeftBtn")
        self.horizontalLayout_3.addWidget(self.LeftBtn)
        self.frame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.MidBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.MidBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.MidBtn.setSizeIncrement(QtCore.QSize(0, 0))
        self.MidBtn.setIconSize(QtCore.QSize(16, 16))
        self.MidBtn.setCheckable(False)
        self.MidBtn.setDefault(False)
        self.MidBtn.setFlat(False)
        self.MidBtn.setObjectName("MidBtn")
        self.horizontalLayout_3.addWidget(self.MidBtn)
        self.frame_3 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.RightBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.RightBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.RightBtn.setObjectName("RightBtn")
        self.horizontalLayout_3.addWidget(self.RightBtn)
        self.frame_5 = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(270, 110, 191, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.BackBtn = QtWidgets.QPushButton(self.frame)
        self.BackBtn.setGeometry(QtCore.QRect(110, 110, 91, 41))
        self.BackBtn.setObjectName("BackBtn")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(540, 150, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(610, 180, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(620, 170, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LeftLabel.setText(_translate("Dialog", "TextLabel"))
        self.MidLabel.setText(_translate("Dialog", "TextLabel"))
        self.RightLabel.setText(_translate("Dialog", "TextLabel"))
        self.ResultLabel.setText(_translate("Dialog", "TextLabel"))
        self.LeftInfo.setText(_translate("Dialog", "TextLabel"))
        self.MidInfo.setText(_translate("Dialog", "TextLabel"))
        self.RightInfo.setText(_translate("Dialog", "TextLabel"))
        self.LeftBtn.setText(_translate("Dialog", "PushButton"))
        self.MidBtn.setText(_translate("Dialog", "PushButton"))
        self.RightBtn.setText(_translate("Dialog", "PushButton"))
        self.pushButton_5.setText(_translate("Dialog", "PushButton"))
        self.BackBtn.setText(_translate("Dialog", "BackBtn"))
        self.label_9.setText(_translate("Dialog", "OpenKiosk"))
        self.label_10.setText(_translate("Dialog", "Berno & Lazy"))
        self.label_11.setText(_translate("Dialog", "by"))



if __name__ == "__main__":
    from PyQt5.QtWidgets import QApplication
    import sys
    app = QApplication(sys.argv)
    foo = Ui_Dialog()


