# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../qtDesigner/v3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Openkiosk(object):
    def setupUi(self, Openkiosk):
        Openkiosk.setObjectName("Openkiosk")
        Openkiosk.setEnabled(True)
        Openkiosk.resize(1024, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../remake/res/dish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Openkiosk.setWindowIcon(icon)
        Openkiosk.setStatusTip("")
        self.Background = QtWidgets.QLabel(Openkiosk)
        self.Background.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Background.sizePolicy().hasHeightForWidth())
        self.Background.setSizePolicy(sizePolicy)
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.pushButton = QtWidgets.QPushButton(Openkiosk)
        self.pushButton.setGeometry(QtCore.QRect(420, 489, 190, 60))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.Rmain = QtWidgets.QFrame(Openkiosk)
        self.Rmain.setEnabled(True)
        self.Rmain.setGeometry(QtCore.QRect(0, 0, 1031, 601))
        self.Rmain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Rmain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Rmain.setObjectName("Rmain")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Rmain)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 731, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setBold(True)
        font.setWeight(75)
        self.LeftLabel.setFont(font)
        self.LeftLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.LeftLabel.setObjectName("LeftLabel")
        self.horizontalLayout.addWidget(self.LeftLabel)
        self.MidLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setBold(True)
        font.setWeight(75)
        self.MidLabel.setFont(font)
        self.MidLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.MidLabel.setObjectName("MidLabel")
        self.horizontalLayout.addWidget(self.MidLabel)
        self.RightLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setBold(True)
        font.setWeight(75)
        self.RightLabel.setFont(font)
        self.RightLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.RightLabel.setObjectName("RightLabel")
        self.horizontalLayout.addWidget(self.RightLabel)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.Rmain)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 280, 731, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LeftInfo = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.LeftInfo.setFont(font)
        self.LeftInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.LeftInfo.setObjectName("LeftInfo")
        self.horizontalLayout_2.addWidget(self.LeftInfo)
        self.MidInfo = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.MidInfo.setFont(font)
        self.MidInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.MidInfo.setObjectName("MidInfo")
        self.horizontalLayout_2.addWidget(self.MidInfo)
        self.RightInfo = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.RightInfo.setFont(font)
        self.RightInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.RightInfo.setObjectName("RightInfo")
        self.horizontalLayout_2.addWidget(self.RightInfo)
        self.frame = QtWidgets.QFrame(self.Rmain)
        self.frame.setGeometry(QtCore.QRect(10, 370, 731, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 731, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LeftBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.LeftBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.LeftBtn.setObjectName("LeftBtn")
        self.horizontalLayout_3.addWidget(self.LeftBtn)
        self.MidBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.MidBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.MidBtn.setSizeIncrement(QtCore.QSize(0, 0))
        self.MidBtn.setIconSize(QtCore.QSize(16, 16))
        self.MidBtn.setCheckable(False)
        self.MidBtn.setDefault(False)
        self.MidBtn.setFlat(False)
        self.MidBtn.setObjectName("MidBtn")
        self.horizontalLayout_3.addWidget(self.MidBtn)
        self.RightBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.RightBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.RightBtn.setObjectName("RightBtn")
        self.horizontalLayout_3.addWidget(self.RightBtn)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(490, 150, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(610, 180, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(590, 170, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 70, 731, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BackBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.BackBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.BackBtn.setObjectName("BackBtn")
        self.horizontalLayout_4.addWidget(self.BackBtn)
        self.CatBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.CatBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.CatBtn.setObjectName("CatBtn")
        self.horizontalLayout_4.addWidget(self.CatBtn)
        self.FinalBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.FinalBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.FinalBtn.setObjectName("FinalBtn")
        self.horizontalLayout_4.addWidget(self.FinalBtn)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Rmain)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(760, 20, 251, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ItemList = QtWidgets.QListView(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ItemList.setFont(font)
        self.ItemList.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ItemList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ItemList.setObjectName("ItemList")
        self.verticalLayout.addWidget(self.ItemList)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.ResultLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("나눔고딕 ExtraBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ResultLabel.setFont(font)
        self.ResultLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ResultLabel.setObjectName("ResultLabel")
        self.verticalLayout.addWidget(self.ResultLabel)
        self.frame.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.verticalLayoutWidget.raise_()
        self.mighty = QtWidgets.QFrame(Openkiosk)
        self.mighty.setGeometry(QtCore.QRect(0, 0, 1021, 591))
        self.mighty.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mighty.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mighty.setObjectName("mighty")
        self.RiceImage = QtWidgets.QLabel(self.mighty)
        self.RiceImage.setGeometry(QtCore.QRect(10, 10, 200, 200))
        self.RiceImage.setFrameShape(QtWidgets.QFrame.Box)
        self.RiceImage.setObjectName("RiceImage")
        self.NoodleImage = QtWidgets.QLabel(self.mighty)
        self.NoodleImage.setGeometry(QtCore.QRect(280, 10, 200, 200))
        self.NoodleImage.setFrameShape(QtWidgets.QFrame.Box)
        self.NoodleImage.setObjectName("NoodleImage")
        self.MeetImage = QtWidgets.QLabel(self.mighty)
        self.MeetImage.setGeometry(QtCore.QRect(550, 10, 200, 200))
        self.MeetImage.setFrameShape(QtWidgets.QFrame.Box)
        self.MeetImage.setObjectName("MeetImage")
        self.SoupImage = QtWidgets.QLabel(self.mighty)
        self.SoupImage.setGeometry(QtCore.QRect(820, 10, 200, 200))
        self.SoupImage.setFrameShape(QtWidgets.QFrame.Box)
        self.SoupImage.setObjectName("SoupImage")
        self.SpicyImage = QtWidgets.QLabel(self.mighty)
        self.SpicyImage.setGeometry(QtCore.QRect(10, 260, 200, 200))
        self.SpicyImage.setFrameShape(QtWidgets.QFrame.Box)
        self.SpicyImage.setObjectName("SpicyImage")
        self.FriedImage = QtWidgets.QLabel(self.mighty)
        self.FriedImage.setGeometry(QtCore.QRect(280, 260, 200, 200))
        self.FriedImage.setFrameShape(QtWidgets.QFrame.Box)
        self.FriedImage.setObjectName("FriedImage")
        self.OilImage = QtWidgets.QLabel(self.mighty)
        self.OilImage.setGeometry(QtCore.QRect(550, 260, 200, 200))
        self.OilImage.setFrameShape(QtWidgets.QFrame.Box)
        self.OilImage.setObjectName("OilImage")
        self.HotImage = QtWidgets.QLabel(self.mighty)
        self.HotImage.setGeometry(QtCore.QRect(820, 260, 200, 200))
        self.HotImage.setFrameShape(QtWidgets.QFrame.Box)
        self.HotImage.setObjectName("HotImage")
        self.progressBar = QtWidgets.QProgressBar(self.mighty)
        self.progressBar.setGeometry(QtCore.QRect(10, 560, 1001, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.RiceBtn = QtWidgets.QCheckBox(self.mighty)
        self.RiceBtn.setGeometry(QtCore.QRect(10, 210, 201, 41))
        self.RiceBtn.setObjectName("RiceBtn")
        self.NoodleBtn = QtWidgets.QCheckBox(self.mighty)
        self.NoodleBtn.setGeometry(QtCore.QRect(280, 210, 201, 41))
        self.NoodleBtn.setObjectName("NoodleBtn")
        self.FriedBtn = QtWidgets.QCheckBox(self.mighty)
        self.FriedBtn.setGeometry(QtCore.QRect(280, 460, 201, 41))
        self.FriedBtn.setObjectName("FriedBtn")
        self.SpicyBtn = QtWidgets.QCheckBox(self.mighty)
        self.SpicyBtn.setGeometry(QtCore.QRect(10, 460, 201, 41))
        self.SpicyBtn.setObjectName("SpicyBtn")
        self.MeetBtn = QtWidgets.QCheckBox(self.mighty)
        self.MeetBtn.setGeometry(QtCore.QRect(550, 210, 201, 41))
        self.MeetBtn.setObjectName("MeetBtn")
        self.OilBtn = QtWidgets.QCheckBox(self.mighty)
        self.OilBtn.setGeometry(QtCore.QRect(550, 460, 201, 41))
        self.OilBtn.setObjectName("OilBtn")
        self.SoupBtn = QtWidgets.QCheckBox(self.mighty)
        self.SoupBtn.setGeometry(QtCore.QRect(820, 210, 201, 41))
        self.SoupBtn.setObjectName("SoupBtn")
        self.HotBtn = QtWidgets.QCheckBox(self.mighty)
        self.HotBtn.setGeometry(QtCore.QRect(820, 460, 201, 41))
        self.HotBtn.setObjectName("HotBtn")
        self.CompleteBtn = QtWidgets.QPushButton(self.mighty)
        self.CompleteBtn.setGeometry(QtCore.QRect(279, 512, 201, 41))
        self.CompleteBtn.setObjectName("CompleteBtn")
        self.BackBtn_2 = QtWidgets.QPushButton(self.mighty)
        self.BackBtn_2.setGeometry(QtCore.QRect(11, 512, 201, 41))
        self.BackBtn_2.setObjectName("BackBtn_2")
        self.VoiceBtn = QtWidgets.QPushButton(self.mighty)
        self.VoiceBtn.setGeometry(QtCore.QRect(547, 512, 201, 41))
        self.VoiceBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.VoiceBtn.setObjectName("VoiceBtn")
        self.Rmain.raise_()
        self.mighty.raise_()
        self.Background.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Openkiosk)
        QtCore.QMetaObject.connectSlotsByName(Openkiosk)

    def retranslateUi(self, Openkiosk):
        _translate = QtCore.QCoreApplication.translate
        Openkiosk.setWindowTitle(_translate("Openkiosk", "OpenKiosk"))
        self.LeftLabel.setText(_translate("Openkiosk", "LeftLabel"))
        self.MidLabel.setText(_translate("Openkiosk", "MidLabel"))
        self.RightLabel.setText(_translate("Openkiosk", "RightLabel"))
        self.LeftInfo.setText(_translate("Openkiosk", "LeftInfo"))
        self.MidInfo.setText(_translate("Openkiosk", "MidInfo"))
        self.RightInfo.setText(_translate("Openkiosk", "RightInfo"))
        self.LeftBtn.setText(_translate("Openkiosk", "중식"))
        self.MidBtn.setText(_translate("Openkiosk", "한식"))
        self.RightBtn.setText(_translate("Openkiosk", "일식"))
        self.label_9.setText(_translate("Openkiosk", "OpenKiosk"))
        self.label_10.setText(_translate("Openkiosk", "Berno & Lazy"))
        self.label_11.setText(_translate("Openkiosk", "by"))
        self.BackBtn.setText(_translate("Openkiosk", "뒤로"))
        self.CatBtn.setText(_translate("Openkiosk", "뭘 골라야하지"))
        self.FinalBtn.setText(_translate("Openkiosk", "최종결정"))
        self.ResultLabel.setText(_translate("Openkiosk", "메뉴를 골라주세요"))
        self.RiceImage.setText(_translate("Openkiosk", "RiceImage"))
        self.NoodleImage.setText(_translate("Openkiosk", "NoodleImage"))
        self.MeetImage.setText(_translate("Openkiosk", "MeetImage"))
        self.SoupImage.setText(_translate("Openkiosk", "SoupImage"))
        self.SpicyImage.setText(_translate("Openkiosk", "SpicyImage"))
        self.FriedImage.setText(_translate("Openkiosk", "FriedImage"))
        self.OilImage.setText(_translate("Openkiosk", "OilImage"))
        self.HotImage.setText(_translate("Openkiosk", "HotImage"))
        self.RiceBtn.setText(_translate("Openkiosk", "RiceBtn"))
        self.NoodleBtn.setText(_translate("Openkiosk", "NoodleBtn"))
        self.FriedBtn.setText(_translate("Openkiosk", "FriedBtn"))
        self.SpicyBtn.setText(_translate("Openkiosk", "SpicyBtn"))
        self.MeetBtn.setText(_translate("Openkiosk", "MeetBtn"))
        self.OilBtn.setText(_translate("Openkiosk", "OilBtn"))
        self.SoupBtn.setText(_translate("Openkiosk", "SoupBtn"))
        self.HotBtn.setText(_translate("Openkiosk", "HotBtn"))
        self.CompleteBtn.setText(_translate("Openkiosk", "확인"))
        self.BackBtn_2.setText(_translate("Openkiosk", "뒤로"))
        self.VoiceBtn.setText(_translate("Openkiosk", "직접 말하기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Openkiosk = QtWidgets.QDialog()
    ui = Ui_Openkiosk()
    ui.setupUi(Openkiosk)
    Openkiosk.show()
    sys.exit(app.exec_())

